services:
  - type: web
    name: arsrc-info-management-api
    runtime: python
    rootDir: backend
    preDeployCommand: python -m alembic upgrade head
    buildCommand: pip install -r requirements.txt && alembic upgrade head
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PROJECT_NAME
        value: ASHANTI REGIONAL SRC INFORMATION MANAGEMENT SYSTEM
      - key: API_V1_STR
        value: /api/v1
      - key: ENVIRONMENT
        value: production
      - key: CORS_ORIGINS
        value: https://arsrc.vercel.app
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "60"
      - key: REFRESH_TOKEN_EXPIRE_DAYS
        value: "7"
      - key: UPLOAD_DIR
        value: ./uploads
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: arsrc-postgres-db
          property: connectionString

databases:
  - name: arsrc-postgres-db
    databaseName: arsrc_db
    user: arsrc_user